## ──────────────────────────────────────────────
## ExternalSecret: Evaluation service config
## Source: togglemaster/evaluation-service (AWS Secrets Manager)
## Creates K8s Secret: evaluation-service-config
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: evaluation-service-config
  namespace: togglemaster-evaluation
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/component: evaluation
    app.kubernetes.io/part-of: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-us-east-1
    kind: SecretStore
  target:
    name: evaluation-service-config
    creationPolicy: Owner
  data:
    - secretKey: REDIS_URL
      remoteRef:
        key: togglemaster/evaluation-service
        property: REDIS_URL
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: togglemaster/evaluation-service
        property: REDIS_PASSWORD
    - secretKey: SQS_QUEUE_URL
      remoteRef:
        key: togglemaster/evaluation-service
        property: SQS_QUEUE_URL
    - secretKey: DYNAMODB_TABLE
      remoteRef:
        key: togglemaster/evaluation-service
        property: DYNAMODB_TABLE
    - secretKey: AUTH_SERVICE_URL
      remoteRef:
        key: togglemaster/evaluation-service
        property: AUTH_SERVICE_URL
    - secretKey: FLAG_SERVICE_URL
      remoteRef:
        key: togglemaster/evaluation-service
        property: FLAG_SERVICE_URL
    - secretKey: TARGETING_SERVICE_URL
      remoteRef:
        key: togglemaster/evaluation-service
        property: TARGETING_SERVICE_URL
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: togglemaster/evaluation-service
        property: SERVICE_API_KEY